# Site settings
title: Adam Cordingley
email: adam@repoweredrobotics.com
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from


