# Site settings
title: Adam Cordingley
email: adam@acordingley.us
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# HTML Snippets
default-nav: "
<div id=\"nav\" > 
  <a href=\"index.html\" id=\"link\">Home</a> 
  <!--<a href=\"cwru.html\"     id=\"link\">CWRU</a> 
  <a href=\"research.html\" id=\"link\">Marshall</a>--> 
  <a href=\"about.html\"    id=\"link\">About</a> 
  <a href=\"contact.html\"  id=\"link\">Contact</a> 
</div>"


